<section>
  <?php require '_header.phtml' ?>

  <article>
    <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Email</th>
          <th>CEP</th>
          <th>Telefone</th>
          <th>Cidade</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->clients as $client): ?>
        <tr>
          <td><?= $client->getId() ?></td>
          <td><?= $client->getName() ?></td>
          <td><?= $client->getEmail() ?></td>
          <td><?= $client->getAddressCep() ?></td>
          <td><?= $client->getPhone() ?></td>
          <td><?= $client->getCity()->getName() ?></td>
          <td>
            <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/pessoa-juridica", '', '', 'class="zoom icon"') ?>
            <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/editar-pessoa-juridica", '', '', 'class="edit icon"') ?>
            <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/deletar-pessoa-juridica", '', 'data-confirm="Tem certeza que deseja deletar?"', 'class="trash icon"') ?>
          </td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>
</article>
</section>
