<section>
  <header class="ui dividing header">
    <h2><?= $this->title ?></h2>
  </header>
  <article>

    <div class="ui segment">
      <form class="ui form client">


        <div class="two fields">
          <div class="field">
            <label>Nome </label>
            <input type="text" id="client['name']" name="client[name]" value="<?= $this->client->getName() ?>" disabled>
          </div>
          <div class="field">
            <label>Email</label>
            <input type="text" id="client['email']" name="client[email]" value="<?= $this->client->getEmail() ?>" disabled>
          </div>
        </div>

        <div class="four fields">

            <div class="field">
              <label> CNPJ </label>
              <input type="text" id="client_cnpj" name="client[cnpj]"  value="<?= $this->client->getCnpj() ?>" disabled>
            </div>
            <div class="field">
              <label>Razão social</label>
              <input type="text" id="client['companyName']" name="client[companyName]"  value="<?= $this->client->getCompanyName() ?>" disabled>
            </div>


          <div class="field">
            <label>Telefone</label>
            <input type="text" id="client_phone" name="client[phone]" value="<?= $this->client->getPhone() ?>" disabled>
          </div>

          <div class="field">
            <label>Cidade</label>
            <select name="client[city_id]" class="ui fluid dropdown" disabled>
                <option>
                  <?= $this->client->getCity()->getName() ?>
                </option>
            </select>
          </div>
        </div>

        <div class="three fields">
          <div class="field">
              <label>Endereço</label>
                <input type="text" id="client['address']" name="client[address]" value="<?= $this->client->getAddress() ?>" disabled>
            </div>
            <div class="field">
              <label>Número</label>
                <input type="text" id="client['address_number']" name="client[address_number]" value="<?= $this->client->getAddressNumber() ?>" disabled>
            </div>
            <div class="field">
              <label>CEP</label>
                <input type="text" id="client_cep" name="client[address_cep]" value="<?= $this->client->getAddressCep() ?>" disabled>
            </div>
        </div>

        <div class="ui buttons">
          <?= ViewHelpers::linkTo("/clientes/pessoa-juridica", 'Voltar', 'class="ui labeled icon button"', 'class="reply icon"') ?>
        </div>
        </form>
      </div>
    </div>

</article>
</section>
