
  <div class="ui segment">
    <form class="ui form client" action="<?= $this->action ?>" method="POST">

     <div class="required field"><label class="ui dividing header">Campos obrigatórios</label></div>

      <div class="two fields">
        <div class="required field <?= $this->client->getErrors('name') ? 'error' : '' ?>">
          <label>Nome </label>
          <input type="text" id="client['name']" name="client[name]" placeholder="nome" value="<?= $this->client->getName() ?>">
          <div class="ui pointing <?= $this->client->getErrors('name') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('name') ?></div>
        </div>
        <div class="required field <?= $this->client->getErrors('email') ? 'error' : '' ?>">
          <label>Email</label>
          <input type="text" id="client['email']" name="client[email]" placeholder="email"  value="<?= $this->client->getEmail() ?>">
          <div class="ui pointing <?= $this->client->getErrors('email') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('email') ?></div>
        </div>
      </div>

      <div class="four fields">

        <div class="required field <?= $this->client->getErrors('cpf') ? 'error' : '' ?>">
          <label>CPF</label>
          <input type="text" id="client_cpf" name="client[cpf]" placeholder="cpf" value="<?= $this->client->getCpf() ?>">
          <div class="ui pointing <?= $this->client->getErrors('cpf') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('cpf') ?></div>
        </div>
        <div class="required field <?= $this->client->getErrors('dateOfBirth') ? 'error' : '' ?>">
          <label>Data de nascimento</label>
          <input type="date" id="clinet['date_of_birth']" name="client[date_of_birth]" placeholder=" ** / ** / ****" value="<?= $this->client->getDateOfBirth() ?>">
          <div class="ui pointing <?= $this->client->getErrors('dateOfBirth') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('dateOfBirth') ?></div>
        </div>

        <div class="required field <?= $this->client->getErrors('phone') ? 'error' : '' ?>">
          <label>Telefone</label>
          <input type="text" id="client_phone" name="client[phone]" placeholder="telefone" value="<?= $this->client->getPhone() ?>">
          <div class="ui pointing <?= $this->client->getErrors('phone') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('phone') ?></div>
        </div>

        <div class="required field">
          <label>Cidade</label>
          <select name="client[city_id]" class="ui fluid dropdown <?= $this->client->getErrors('city_id') ? 'error' : '' ?>">
            <option value="">Selecione uma cidade</option>
            <?php foreach($this->cities as $city) : ?>
              <option value='<?= $city->getId() ?>'
                  <?= ($city->getId() === $this->client->getCityId()) ? 'selected' :  '' ?> >
                <?=  $city->getName() ?>
              </option>
            <?php endForeach; ?>
          </select>
        </div>
      </div>

      <div class="three fields">
        <div class="required field <?= $this->client->getErrors('address') ? 'error' : '' ?>">
            <label>Endereço</label>
              <input type="text" id="client['address']" name="client[address]" placeholder="Street Address"  value="<?= $this->client->getAddress() ?>">
              <div class="ui pointing <?= $this->client->getErrors('address') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('address') ?></div>
          </div>
          <div class="required field <?= $this->client->getErrors('address_number') ? 'error' : '' ?>">
            <label>Número</label>
              <input type="text" id="client['address_number']" name="client[address_number]" placeholder="Número"  value="<?= $this->client->getAddressNumber() ?>">
              <div class="ui pointing <?= $this->client->getErrors('address_number') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('address_number') ?></div>
          </div>
          <div class="required field <?= $this->client->getErrors('address_cep') ? 'error' : '' ?>">
            <label>CEP</label>
              <input type="text" id="client_cep" name="client[address_cep]" placeholder="cep"  value="<?= $this->client->getAddressCep() ?>">
              <div class="ui pointing <?= $this->client->getErrors('address_cep') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('address_cep') ?></div>
          </div>
      </div>

      <div class="align-center">
        <div class="ui buttons">
          <?= ViewHelpers::linkTo("/clientes/pessoa-fisica", 'Cancelar', 'class="ui labeled icon button"', 'class="reply icon"') ?>
          <div class="or"></div>
          <?= ViewHelpers::buttonTo($this->submit, 'class="ui right labeled primary icon button"', 'class="right arrow icon"') ?>
        </div>
      </div>
      </form>
    </div>
  </div>
