<section>
  <?php require "_header.phtml" ?>

  <article>
    <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Email</th>
          <th>CEP</th>
          <th>Telefone</th>
          <th>Cidade</th>
          <th>Tipo</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->clients as $client): ?>
        <tr>
          <td><?= $client->getId() ?></td>
          <td><?= $client->getName() ?></td>
          <td><?= $client->getEmail() ?></td>
          <td><?= ViewHelpers::cepFormat($client->getAddressCep()) ?></td>
          <td><?= ViewHelpers::phoneFormat($client->getPhone()) ?></td>
          <td><?= $client->getCity()->getName() ?></td>
          <td><?= ViewHelpers::clientType($client->getType()) ?></td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>

</article>
</section>
