<section>
  <header class="ui dividing header">
    <h2><?= $this->title ?></h2>
  </header>

  <div class="clearfix">
    <?= ViewHelpers::linkTo("/clientes/nova-pessoa-fisica", 'Novo cliente', 'class="ui left floated primary labeled icon button"', 'class="add circle icon"') ?>

    <select class="ui dropdown" onChange="window.location.href=this.value">
      <option value="">Selecione ...</option>
      <option value="<?= ViewHelpers::urlFor("/clientes", '') ?>">Todos os clientes</option>
      <option value="<?= ViewHelpers::urlFor("/clientes/pessoa-fisica", '') ?>">Clientes pessoa física</option>
      <option value="<?= ViewHelpers::urlFor("/clientes/pessoa-juridica", '') ?>">Clientes pessoa jurídica</option>
    </select>
  </div>

  <article>
    <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Email</th>
          <th>CEP</th>
          <th>Telefone</th>
          <th>Cidade</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->clients as $client): ?>
        <tr>
          <td><?= $client->getId() ?></td>
          <td><?= $client->getName() ?></td>
          <td><?= $client->getEmail() ?></td>
          <td><?= $client->getAddressCep() ?></td>
          <td><?= $client->getPhone() ?></td>
          <td><?= $client->getCity()->getName() ?></td>
          <td>
            <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/pessoa-fisica", '', '', 'class="zoom icon"') ?>
            <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/editar-pessoa-fisica", '', '', 'class="edit icon"') ?>
            <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/deletar-pessoa-fisica", '', 'data-confirm="Tem certeza que deseja deletar?"', 'class="trash icon"') ?>
          </td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>
  </div>
</div>
</article>
</section>
