<form role="form" action="<?= ViewHelpers::urlFor($this->action) ?>" method="POST">

  <div class="form-group <?= $this->user->getErrors('name') ? 'has-error' : '' ?>">
    <label class="control-label" for="user_name">Nome:*</label>
    <input type="text" class="form-control" name="user[name]" value="<?= $this->user->getName() ?>"
           id="user_name" placeholder="Seu nome">
    <p class="help-block"><?= $this->user->getErrors('name') ?></p>
  </div>

  <div class="form-group <?= $this->user->getErrors('email') ? 'has-error' : '' ?>">
    <label class="control-label" for="user_email">Email:*</label>
    <input type="text" class="form-control" name="user[email]" value="<?= $this->user->getEmail() ?>"
           id="user_email" placeholder="Seu nome">
    <p class="help-block"><?= $this->user->getErrors('email') ?></p>
  </div>

  <div class="form-group <?= $this->user->getErrors('password') ? 'has-error' : '' ?>">
    <label class="control-label" for="user_password">Senha:*</label>
    <input type="password" class="form-control" name="user[password]" id="user_password">
    <p class="help-block"><?= $this->user->getErrors('password') ?></p>
  </div>

  <button type="submit" class="btn btn-primary"> <?= $this->submit ?></button>
</form>
