<form role="form" action="<?= ViewHelpers::urlFor($this->action) ?>" method="POST">

  <div class="ui form">
    <div class="field <?= $this->user->getErrors('name') ? 'error' : '' ?>">
      <label class="control-label" for="user_name">Nome:*</label>
      <input type="text" class="form-control" name="user[name]" value="<?= $this->user->getName() ?>"
             id="user_name" placeholder="Seu nome">
      <div class="ui pointing <?= $this->user->getErrors('name') ? 'red basic label' : '' ?>"><?= $this->user->getErrors('name') ?></div>
    </div>

    <div class="field <?= $this->user->getErrors('email') ? 'error' : '' ?>">
      <label class="control-label" for="user_email">Email:*</label>
      <input type="text" class="form-control" name="user[email]" value="<?= $this->user->getEmail() ?>"
             id="user_email" placeholder="Seu nome">
      <div class="ui pointing <?= $this->user->getErrors('email') ? 'red basic label' : '' ?>"><?= $this->user->getErrors('email') ?></div>
    </div>

    <div class="field <?= $this->user->getErrors('password') ? 'error' : '' ?>">
      <label class="control-label" for="user_password">Senha:*</label>
      <input type="password" class="form-control" name="user[password]" id="user_password">
      <div class="ui pointing <?= $this->user->getErrors('password') ? 'red basic label' : '' ?>"><?= $this->user->getErrors('password') ?></div>
    </div>

    <button type="submit" class="ui primary button"> <?= $this->submit ?></button>
  </div>
</form>
