
  <div class="ui segment">
    <form class="ui form client" action="<?= $this->action ?>" method="POST">

     <div class="required field"><label class="ui dividing header">Campos obrigatórios</label></div>

      <div class="two fields">
        <div class="required field <?= $this->client->getErrors('name') ? 'error' : '' ?>">
          <label>Nome </label>
          <input type="text" id="client['name']" name="client[name]" placeholder="nome" value="<?= $this->client->getName() ?>">
          <div class="ui pointing <?= $this->client->getErrors('name') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('name') ?></div>
        </div>
        <div class="required field <?= $this->client->getErrors('email') ? 'error' : '' ?>">
          <label>Email</label>
          <input type="text" id="client['email']" name="client[email]" placeholder="email"  value="<?= $this->client->getEmail() ?>">
          <div class="ui pointing <?= $this->client->getErrors('email') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('email') ?></div>
        </div>
      </div>

      <div class="four fields">
      <div class="required field <?= $this->client->getErrors('phone') ? 'error' : '' ?>">
        <label> CNPJ </label>
        <input type="text" id="client['cnpj']" name="client[cnpj]" placeholder="cnpj" value="<?= $this->client->getCnpj() ?>">
        <div class="ui pointing <?= $this->client->getErrors('cnpj') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('cnpj') ?></div>
      </div>
      <div class="required field <?= $this->client->getErrors('companyName') ? 'error' : '' ?>">
        <label>Razão social</label>
        <input type="text" id="client['companyName']" name="client[companyName]"  value="<?= $this->client->getCompanyName() ?>">
        <div class="ui pointing <?= $this->client->getErrors('companyName') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('companyName') ?></div>
      </div>


        <div class="required field <?= $this->client->getErrors('phone') ? 'error' : '' ?>">
          <label>Telefone</label>
          <input type="text" id="client['phone']" name="client[phone]" placeholder="telefone" value="<?= $this->client->getPhone() ?>">
          <div class="ui pointing <?= $this->client->getErrors('phone') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('phone') ?></div>
        </div>

        <div class="required field">
          <label>Cidade</label>
          <select name="client[city_id]" class="ui fluid dropdown <?= $this->client->getErrors('city_id') ? 'error' : '' ?>">
            <option value="">Selecione uma cidade</option>
            <?php foreach($this->cities as $city) : ?>
              <option value='<?= $city->getId() ?>'
                <?= ($city->getId() === $this->client->getCityId()) ? 'selected' :  '' ?> >
                <?=  $city->getName() ?>
              </option>
            <?php endForeach; ?>
          </select>
        </div>
      </div>

      <div class="three fields">
        <div class="required field <?= $this->client->getErrors('address') ? 'error' : '' ?>">
            <label>Endereço</label>
              <input type="text" id="client['address']" name="client[address]" placeholder="Street Address"  value="<?= $this->client->getAddress() ?>">
              <div class="ui pointing <?= $this->client->getErrors('address') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('address') ?></div>
          </div>
          <div class="required field <?= $this->client->getErrors('addressNumber') ? 'error' : '' ?>">
            <label>Número</label>
              <input type="text" id="client['address_number']" name="client[address_number]" placeholder="Número"  value="<?= $this->client->getAddressNumber() ?>">
              <div class="ui pointing <?= $this->client->getErrors('addressNumber') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('addressNumber') ?></div>
          </div>
          <div class="required field <?= $this->client->getErrors('addressCep') ? 'error' : '' ?>">
            <label>CEP</label>
              <input type="text" id="client['address_cep']" name="client[address_cep]" placeholder="cep"  value="<?= $this->client->getAddressCep() ?>">
              <div class="ui pointing <?= $this->client->getErrors('addressCep') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('addressCep') ?></div>
          </div>
      </div>

      <input type="hidden" name="client[type]" value="<?= $this->type ?>">

      <div class="align-center">
        <div class="ui buttons">
          <?= ViewHelpers::linkTo("/clientes", 'Cancelar', 'class="ui labeled icon button"', 'class="reply icon"') ?>
          <div class="or"></div>
          <?= ViewHelpers::buttonTo($this->submit, 'class="ui right labeled primary icon button"', 'class="right arrow icon"') ?>
        </div>
      </div>
      </form>
    </div>
  </div>
