
  <div class="ui segment">
    <form class="ui form client" action="<?= $this->action ?>" method="POST">

      <h4 class="ui dividing header">Informações do cliente </h4>

      <div class="two fields">
        <div class="field <?= $this->client->getErrors('name') ? 'error' : '' ?>">
          <label>Nome </label>
          <input type="text" id="client_name" name="client[name]" placeholder="nome" value="<?= $this->client->getName() ?>">
          <div class="ui pointing <?= $this->client->getErrors('name') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('name') ?></div>
        </div>
        <div class="field <?= $this->client->getErrors('email') ? 'error' : '' ?>">
          <label>Email</label>
          <input type="text" id="client['email']" name="client[email]" placeholder="email"  value="<?= $this->client->getEmail() ?>">
          <div class="ui pointing <?= $this->client->getErrors('email') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('email') ?></div>
        </div>
      </div>

      <div class="four fields">
        <?php ($this->type == 1) ? require '_form_pi.phtml' : require '_form_pc.phtml'; ?>
        <div class="field <?= $this->client->getErrors('phone') ? 'error' : '' ?>">
          <label>Telefone</label>
          <input type="text" id="client['phone']" name="client[phone]" placeholder="telefone" value="<?= $this->client->getPhone() ?>">
          <div class="ui pointing <?= $this->client->getErrors('phone') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('phone') ?></div>
        </div>

        <div class="field">
          <label>Cidade</label>
          <select class="ui fluid dropdown" name="client[city]">
            <option value="">Selecione uma cidade</option>
            <?php foreach($this->cities as $city) : ?>
              <option value='<?= $city->getId() ?>'
                <?= ($city->getId() === $this->client->getCity()) ? 'selected' :  '' ?> >
                <?=  $city->getName() ?>
              </option>
            <?php endForeach; ?>
          </select>
        </div>
      </div>

      <div class="three fields">
        <div class="field <?= $this->client->getErrors('address') ? 'error' : '' ?>">
            <label>Endereço</label>
              <input type="text" id="client['address']" name="client[address]" placeholder="Street Address"  value="<?= $this->client->getAddress() ?>">
              <div class="ui pointing <?= $this->client->getErrors('address') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('address') ?></div>
          </div>
          <div class="field <?= $this->client->getErrors('addressNumber') ? 'error' : '' ?>">
            <label>Número</label>
              <input type="text" id="client['address_number']" name="client[address_number]" placeholder="Número"  value="<?= $this->client->getAddressNumber() ?>">
              <div class="ui pointing <?= $this->client->getErrors('addressNumber') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('addressNumber') ?></div>
          </div>
          <div class="field <?= $this->client->getErrors('addressCep') ? 'error' : '' ?>">
            <label>CEP</label>
              <input type="text" id="client['address_cep']" name="client[address_cep]" placeholder="cep"  value="<?= $this->client->getAddressCep() ?>">
              <div class="ui pointing <?= $this->client->getErrors('addressCep') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('addressCep') ?></div>
          </div>
      </div>

      <input type="hidden" name="client[type]" value="<?= $this->type ?>">

      <div class="align-center">
        <div class="ui buttons">
          <?= $this->linkTo("/clientes", 'Cancelar', 'class="ui button"') ?>
          <div class="or"></div>
          <button type="submit" class="ui positive button"> <?= $this->submit ?> </button>
        </div>
      </form>
    </div>
