
<div class="required field <?= $this->client->getErrors('phone') ? 'error' : '' ?>">
  <label> CNPJ </label>
  <input type="text" id="client['cnpj']" name="client[cnpj]" placeholder="cnpj" value="<?= $this->client->getCnpj() ?>">
  <div class="ui pointing <?= $this->client->getErrors('cnpj') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('cnpj') ?></div>
</div>
<div class="required field <?= $this->client->getErrors('companyName') ? 'error' : '' ?>">
  <label>Razão social</label>
  <input type="text" id="client['companyName']" name="client[companyName]"  value="<?= $this->client->getCompanyName() ?>">
  <div class="ui pointing <?= $this->client->getErrors('companyName') ? 'red basic label' : '' ?>"><?= $this->client->getErrors('companyName') ?></div>
</div>
