<section>
      <table class="ui compact celled definition table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Email</th>
          <th>CEP</th>
          <th>Telefone</th>
          <th>Cidade</th>
          <th>Data de criação</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
          foreach ($this->clients as $client): ?>
          <tr>
            <td><?= $client->getId() ?></td>
            <td><?= $client->getName() ?></td>
            <td><?= $client->getEmail() ?></td>
            <td><?= $client->getAddressCep() ?></td>
            <td><?= $client->getPhone() ?></td>
            <td><?= $client->getCityId()->getName() ?></td>
            <td><?= ViewHelpers::dateFormat($client->getCreatedAt()); ?></td>
            <td>
              <?= ViewHelpers::linkTo("/clientes/{$client->getId()}", '', '', 'class="zoom icon"') ?>
              <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/editar/{$client->getType()}", '', '', 'class="edit icon"') ?>
              <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/deletar", '', 'data-confirm="Tem certeza que deseja deletar?"', 'class="trash icon"') ?>
            </td>
          </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <th colspan="8">
            <?= ViewHelpers::linkTo("/clientes/novo/1", 'Novo cliente', 'class="ui left floated small primary labeled icon button"', 'class="add circle icon"') ?>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

</section>
