<section>
  <header>
    <h2><?= $this->title ?></h2>
  </header>
  <?= ViewHelpers::linkTo('/clientes/novo', 'Novo cliente', 'class="btn btn-default"') ?>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>CEP</th>
        <th>Telefone</th>
        <th>Cidade</th>
        <th>Criação</th>
      </tr>
    </thead>
    <tbody>
    <?php
      foreach ($this->clients as $client): ?>
      <tr>
        <td><?= $client->getId() ?></td>
        <td><?= $client->getName() ?></td>
        <td><?= $client->getEmail() ?></td>
        <td><?= $client->getAddressCep() ?></td>
        <td><?= $client->getPhone() ?></td>
        <td><?= $client->getCity() ?></td>
        <td><?= ViewHelpers::dateFormat($client->getCreatedAt()); ?></td>
        <td><?= ViewHelpers::linkTo("/clientes/{$client->getId()}/editar", "Editar", 'class="btn btn-primary"') ?></td>
        <td><?= ViewHelpers::linkTo("/clientes/{$client->getId()}/deletar", "Excluir", 'class="btn btn-danger"') ?></td>
      </tr>
    <?php endForeach; ?>
    </tbody>
  </table>

</section>
