
  <div class="ui segment">
    <form class="ui form client">

      <h4 class="ui dividing header">Informações do cliente (pessoa física)</h4>

      <div class="two fields">
        <div class="field">
          <label>Name</label>
          <input type="text" name="shipping[first-name]" placeholder="First Name">
        </div>
        <div class="field">
          <label>Email</label>
          <div class="field">
            <input type="text" name="shipping[last-name]" placeholder="email">
          </div>
        </div>
      </div>

      <div class="three fields">
        <div class="field">
          <label>CPF</label>
          <input type="text" name="shipping[first-name]" placeholder="cpf">
        </div>
        <div class="field">
          <label>Telefone</label>
          <input type="text" name="shipping[last-name]" placeholder="telefone">
        </div>
        <div class="field">
          <label>Data de nascimento</label>
          <input type="text" name="shipping[last-name]" placeholder=" ** / ** / ****">
        </div>
      </div>

      <div class="field">
        <label>Endereço</label>
        <div class="fields">
          <div class="eight wide field">
            <input type="text" name="shipping[address]" placeholder="Street Address">
          </div>
          <div class="four wide field">
            <input type="text" name="shipping[address-2]" placeholder="Número">
          </div>
          <div class="four wide field">
            <input type="text" name="shipping[address-2]" placeholder="CEP">
          </div>
        </div>
      </div>

      <div class="two fields">
        <div class="field">
          <label>Estado</label>
          <select class="ui fluid dropdown">
            <option value="">State</option>
            <option value="AL">Alabama</option>
          </select>
        </div>
        <div class="field">
          <label>Cidade</label>
          <div class="ui fluid search selection dropdown">
            <input type="hidden" name="country">
            <i class="dropdown icon"></i>
            <div class="default text">Select Country</div>
            <div class="menu">
              <div class="item" data-value="af"><i class="af flag"></i>Afghanistan</div>
            </div>
          </div>
        </div>
      </div>

      <div class="align-center">
        <div class="ui buttons">
          <button class="ui button">Cancelar</button>
          <div class="or"></div>
          <button class="ui positive button">Cadastrar</button>
        </div>
      </form>
    </div>
