<form class="form-horizontal">

  <fieldset>

    <!-- Form Name -->
    <legend> Cadastro de pessoa física </legend>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Nome</label>
      <div class="col-md-5">
        <input id="textinput" name="textinput" type="text" placeholder="nome" class="form-control input-md">
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">Email</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="email" class="form-control input-md">
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">CPF</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="cpf" class="form-control input-md">

      </div>
    </div>

    <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">Cidade</label>
      <div class="col-md-5">
        <select id="" name="" class="form-control">
          <option value="1">Selecione</option>
          <option value="2">Guarapuava</option>
        </select>
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">Data de nascimento</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="" class="form-control input-md">

      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">Telefone</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="" class="form-control input-md">

      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">Endereço</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="" class="form-control input-md">

      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">CEP</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="" class="form-control input-md">

      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="">Número</label>
      <div class="col-md-5">
        <input id="" name="" type="text" placeholder="" class="form-control input-md">

      </div>
    </div>

    <!-- Button (Double) -->
    <div class="form-group">
      <label class="col-md-4 control-label" for=""></label>
      <div class="col-md-8">
        <button id="" name="" class="btn btn-success">Cadastrar</button>
        <?= ViewHelpers::linkTo("/clientes", "Cancelar", 'class="btn btn-danger"') ?>
      </div>
    </div>

  </fieldset>
</form>
