<section>
  <header class="ui dividing header">
    <h2><?= $this->title ?></h2>
  </header>

  <div class="clearfix">
    <?= ViewHelpers::linkTo("/pedidos/novo", 'Novo pedido', 'class="ui floated small primary labeled icon button"', 'class="add circle icon"') ?>

    <select class="ui dropdown" onChange="window.location.href=this.value">
      <option value="">Selecione ...</option>
      <option value="<?= ViewHelpers::urlFor("/pedidos", '') ?>">Todos os pedidos</option>
      <option value="<?= ViewHelpers::urlFor("/pedidos/abertos", '') ?>">Pedidos abertos</option>
      <option value="<?= ViewHelpers::urlFor("/pedidos/fechados", '') ?>">Pedidos fechados</option>
    </select>
  </div>

  <article>
    <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Cliente</th>
          <th>Quantidade de produtos</th>
          <th>Total</th>
          <th>Cadastrado em</th>
          <th>Status</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->orders as $order): ?>
        <tr>
          <td><?= $order->getId() ?></td>
          <td><?= $order->getClient()->getName() ?></td>
          <td><?= $order->sum() ?></td>
          <td><?= ViewHelpers::currencyFormat($order->getTotal()) ?></td>
          <td><?= ViewHelpers::dateFormat($order->getCreatedAt()) ?></td>
          <td><?= $order->getStatus() ?></td>
          <td>
            <?= ViewHelpers::linkTo("/pedidos/{$order->getId()}", '', '', 'class="zoom icon"') ?>
            <?php if($order->getStatus() == "Aberto"): ?>
              <?= ViewHelpers::linkTo("/pedidos/{$order->getId()}", '', '', 'class="edit icon"') ?>
            <?php endIf; ?>
            <?= ViewHelpers::linkTo("/pedidos/{$order->getId()}/deletar", '', 'data-confirm="Deseja excluir pedido?"', 'class="trash icon"') ?>
          </td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>
</article>
</section>
