<section>
  <header class="ui dividing header">
    <h2><?= $this->title ?></h2>
  </header>

  <article>
    <table class="ui compact celled definition table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Cliente</th>
          <th>Quantidade de produtos</th>
          <th>Total</th>
          <th>Cadastrado em</th>
          <th>Status</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->orders as $order): ?>
        <tr>
          <td><?= $order->getId() ?></td>
          <td><?= $order->getClient()->getName() ?></td>
          <td><?= $order->sum() ?></td>
          <td><?= ViewHelpers::currencyFormat($order->getTotal()) ?></td>
          <td><?= ViewHelpers::dateFormat($order->getCreatedAt()) ?></td>
          <td><?= $order->getStatus() ?></td>
          <td>
            <?= ViewHelpers::linkTo("/pedidos/{$order->getId()}", '', '', 'class="zoom icon"') ?>
            <?= ViewHelpers::linkTo("/pedidos/{$order->getId()}", '', '', 'class="edit icon"') ?>
            <?= ViewHelpers::linkTo("/pedidos/{$order->getId()}/deletar", '', 'data-confirm="Deseja excluir pedido?"', 'class="trash icon"') ?>
          </td>
        </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <th colspan="8">
              <?= ViewHelpers::linkTo("/pedidos/novo", 'Novo pedido', 'class="ui left floated small primary labeled icon button"', 'class="add circle icon"') ?>
          </th>
        </tr>
      </tfoot>
    </table>
</article>
</section>
