<section>
  <header>
    <h2 class="ui dividing header"><?= $this->title ?></h2>
  </header>
  <article>
    <?php require '_form_order_items.phtml'; ?>

    <table class="ui table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Preço Unitário</th>
          <th>Preço</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->order->getProducts() as $product) : ?>
            <tr>
              <td><?= $product->getId() ?></td>
              <td><?= $product->getName() ?></td>
              <td>
                <?= SellOrderItem::getAmountOfProduct($product->getId(), $this->order->getId()) ?>
                <?= ViewHelpers::linkTo("/pedidos/{$this->order->getId()}/produtos/{$product->getId()}/adicionar", "", '', 'class="add square icon"') ?>
                <?= ViewHelpers::linkTo("/pedidos/{$this->order->getId()}/produtos/{$product->getId()}/remover", '', '', 'class="minus square icon"') ?>
              </td>
              <td><?= $product->getPrice() ?></td>
              <td><?= ViewHelpers::currencyFormat($product->getPrice() * SellOrderItem::getAmountOfProduct($product->getId() , $this->order->getId())) ?></td>
              <td><?= ViewHelpers::linkTo("/pedidos/{$this->order->getId()}/produtos/{$product->getId()}/deletar", '', 'data-confirm="Tem certeza que deseja deletar o produto?"', 'class="trash icon"') ?></td>
            </tr>
      </tbody>
      <?php endForeach; ?>
      <tfoot>
        <th colspan="3"></th>
        <th>TOTAL</th>
        <th colspan="2"></th>
      </tfoots>
    </table>
      <?= ViewHelpers::linkTo("/pedidos/{$this->order->getId()}/fechar", 'Fechar pedido', 'class="ui right floated primary labeled icon button"', 'class="unlock alternate icon"') ?>
  </article>
</section>
