<section>
  <header>
    <h2 class="ui dividing header"><?= $this->title ?></h2>
  </header>

  <div class="ui hidden divider"></div>
  <article>
    <table class="ui table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Preço Unitário</th>
          <th>Preço</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->order->getProducts() as $product) : ?>
            <tr>
              <td><?= $product->getId() ?></td>
              <td><?= $product->getName() ?></td>
              <td><?= $amount = $this->sellOrderItem->getAmountOfProduct($product->getId(), $this->order->getId()) ?></td>
              <td><?= ViewHelpers::currencyFormat($product->getPrice()) ?></td>
              <td><?= $price_amount = ViewHelpers::currencyFormat($product->getPrice() * $amount) ?>
            </tr>
      </tbody>
      <?php endForeach; ?>
      <tfoot>
        <th colspan="3"></th>
        <th>TOTAL</th>
        <th colspan="2"><?= ViewHelpers::currencyFormat($this->order->getTotal()) ?></th>
      </tfoots>
    </table>
      <?= ViewHelpers::linkTo("/pedidos", 'Voltar', 'class="ui left small labeled icon button"', 'class="reply icon"') ?>
  </article>
</section>
