<section>
  <header>
    <h2>Pedido</h2>
  </header>
  <article>
      <p>Cliente : <?= $this->order->getClientId()->getName() ?></p>

    <form role="form" class="ui form" action="<?= ViewHelpers::urlFor('/pedidos/produtos') ?>" method="POST">
      <div class="field">
        <label class="sr-only" for="autocomplete_product_by_id">ID do produto</label>
        <input type="number" id="autocomplete_product_by_id"
          name="product[id]" placeholder="Código do produto" min="0">
      </div>

      <div class="field">
        <label class="sr-only" for="autocomplete_product_by_name"> Nome do Produto </label>
        <input type="text" id="autocomplete_product_by_name"
        name="product[name]" data-url="<?= ViewHelpers::urlFor('/produtos/autocomplete-search') ?>"
        placeholder="Nome do produto">
      </div>

      <input type="hidden" class="form-control" id="order_id" value="<?= $this->order->getId() ?>" name="order[id]">

      <button type="submit"  class="ui primary button">Adicionar</button>
    </form>

    <table class="ui table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nome</th>
          <th>Preço</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->order->getProducts() as $product) : ?>
            <tr>
              <td><?= $product->getId() ?></td>
              <td><?= $product->getName() ?></td>
              <td><?= $product->getPrice() ?></td>
              <td><?= ViewHelpers::linkTo("/pedidos/{$product->getId()}/deletar", "Excluir", 'class="btn btn-danger"') ?></td>
            </tr>
      </tbody>
      <?php endForeach; ?>
    </table>

  </article>
</section>
