
  <div class="ui attached stackable menu">
    <div class="ui container">
      <?= ViewHelpers::linkTo('/', 'Sistema', 'class="item"', 'class="home icon"') ?>
      <?php if (SessionHelpers::isLoggedIn()): ?>
      <div class="ui simple dropdown item">
        Olá Renan
        <i class="dropdown icon"></i>
        <div class="menu">
          <?= ViewHelpers::linkTo('/perfil', 'Perfil', 'class="item"', 'class="settings icon"') ?>
          <?= ViewHelpers::linkTo('/logout', 'Sair', 'class="item"', 'class="sign out icon"') ?>
        </div>
      </div>
      <div class="right item">
        <div class="ui icon input">
          <input class="prompt" type="text" placeholder="search...">
          <i class="search link icon"></i>
        </div>
      </div>
      <?php else: ?>
        <?= ViewHelpers::linkTo('/login', 'Login', 'class="item"', 'class="protect icon"') ?>
      <?php endif ?>
    </div>
    </div>
  </div>
