
  <div class="ui attached stackable menu">
    <div class="ui container">
      <?= ViewHelpers::linkTo('/', 'Sistema', 'class="item"', 'class="home icon"') ?>
      <?php if (SessionHelpers::isLoggedIn()): ?>
      <div class="ui simple dropdown item">
        <i class="user icon"></i> Olá <?= $this->currentEmployee()->getName() ?>
        <i class="dropdown icon"></i>
        <div class="menu">
          <?= ViewHelpers::linkTo('/perfil', 'Perfil', 'class="item"', 'class="settings icon"') ?>
          <?= ViewHelpers::linkTo('/logout', 'Sair', 'class="item"', 'class="sign out icon"') ?>
        </div>
      </div>
      <?php else: ?>
        <?= ViewHelpers::linkTo('/login', 'Login', 'class="item"', 'class="protect icon"') ?>
      <?php endif ?>
    </div>
    </div>
  </div>
