<?php if (SessionHelpers::isLoggedIn()): ?>
  <div class="ui equal width grid">
    <div class="row">
      <div class="ui segment">
        <div class="column">
          <div class="ui vertical menu">
            <div class="item">
              <div class="header">Categorias</div>
              <div class="menu">
                  <?= ViewHelpers::linkTo('/categorias', 'Visualizar categorias', 'class="item"') ?>
                  <?= ViewHelpers::linkTo('/categorias/novo', 'Cadastro de categorias', 'class="item"') ?>
              </div>
            </div>
            <div class="item">
              <div class="header">Pedidos</div>
              <div class="menu">
                <?= ViewHelpers::linkTo('/pedidos', 'Visualizar pedidos', 'class="item"') ?>
                <?= ViewHelpers::linkTo('/pedidos/novo', 'Cadastro de pedidos', 'class="item"') ?>
              </div>
            </div>
            <div class="item">
              <div class="header">Clientes</div>
              <div class="menu">
                <?= ViewHelpers::linkTo('/clientes', 'Visualizar clientes', 'class="item"') ?>
                <?= ViewHelpers::linkTo('/clientes/novo/1', 'Cadastro de cliente físico', 'class="item"') ?>
                <?= ViewHelpers::linkTo('/clientes/novo/2', 'Cadastro de cliente jurídico', 'class="item"') ?>
              </div>
            </div>
            <div class="item">
              <div class="header">Relatórios</div>
              <div class="menu">
                <a class="item">Vendas</a>
                <a class="item">Funcionários</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    <?php endif ?>
