<?php if (SessionHelpers::isLoggedIn()): ?>
  <div class="ui equal width grid">
    <div class="row">
      <div class="ui segment">
        <div class="column">
          <div class="ui vertical menu" id="sidebar">
            <div class="item">
                <div class="header">Clientes</div>
                <div class="menu">
                  <?= ViewHelpers::linkTo('/clientes/pessoa-fisica', 'Visualizar clientes', 'class="item"') ?>
                  <?= ViewHelpers::linkTo('/clientes/nova-pessoa-fisica', 'Cadastro de cliente', 'class="item"') ?>
                </div>
              </div>
              <div class="item">
                <div class="header">Pedidos</div>
                <div class="menu">
                  <?= ViewHelpers::linkTo('/pedidos', 'Visualizar pedidos', 'class="item"') ?>
                  <?= ViewHelpers::linkTo('/pedidos/novo', 'Cadastro de pedidos', 'class="item"') ?>
                </div>
            </div>
            <div class="item">
              <div class="header">Produtos</div>
              <div class="menu">
                  <?= ViewHelpers::linkTo('/produtos', 'Visualizar produtos', 'class="item"') ?>
                  <?= ViewHelpers::linkTo('/produtos/novo', 'Cadastro de produtos', 'class="item"') ?>
              </div>
            </div>
            <div class="item">
              <div class="header">Categorias</div>
              <div class="menu">
                  <?= ViewHelpers::linkTo('/categorias', 'Visualizar categorias', 'class="item"') ?>
                  <?= ViewHelpers::linkTo('/categorias/novo', 'Cadastro de categorias', 'class="item"') ?>
              </div>
            </div>
            <div class="item">
              <div class="header">Relatórios</div>
              <div class="menu">
                <?= ViewHelpers::linkTo('/relatorios/produtos-mais-vendidos', 'Produtos', 'class="item"') ?>
                <?= ViewHelpers::linkTo('/relatorios/funcionarios', 'Funcionarios', 'class="item"') ?>
              </div>
            </div>
          </div>
        </div>
      </div>
    <?php endif ?>
