<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/images/favicon.ico">

    <title><?= ViewHelpers::fullTitle(@$page_title) ?></title>

    <!-- Bootstrap core CSS -->
    <?= ViewHelpers::styleSheetIncludeTag('/bootstrap/css/bootstrap.min.css',
                                          '/bootstrap/css/bootstrap-theme.min.css',
                                          '/bootstrap/css/bootstrap.min.css.map',
                                          '/bootstrap/fonts/font-awesome.min.css',
                                          'application.css') ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- shim is a small library that transparently intercepts API calls and changes the arguments passed -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <?php require "_nav_bar.phtml" ?>

    <!-- Begin page content -->
    <div id="main-container" class="container">

      <?php require "_flash_messages.phtml" ?>

      <article>
        <div class="row row-offcanvas row-offcanvas-right">

          <div class="col-xs-12 col-sm-9">
            <?php require $view; ?>
          </div>

          <?php require "_side_bar.phtml" ?>
        </article>

      </div><!-- #MAIN-CONTAINER -->



      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <?= ViewHelpers::javascriptIncludeTag('jquery-1.11.3.min.js',
                                            'jquery.autocomplete.js',
                                            '/bootstrap/js/bootstrap.min.js',
                                            'application.js') ?>

    </body>
    </html>
