<section>
  <table class="ui compact celled definition table">
    <thead class="full-width">
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Data de criação</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach ($this->categories as $category): ?>
      <tr>
        <td><?= $category->getId() ?></td>
        <td><?= $category->getName() ?></td>
        <td><?= ViewHelpers::dateFormat($category->getCreatedAt()); ?></td>
        <td>
          <?= $this->linkTo("/categorias/{$category->getId()}",'', '', 'class="zoom icon"') ?>
          <?= $this->linkTo("/categorias/{$category->getId()}/editar", '', '', 'class="edit icon"') ?>
          <?= $this->linkTo("/categorias/{$category->getId()}/deletar", '', 'data-confirm="Deseja excluir categoria?"', 'class="trash icon"') ?>
        </td>
      </tr>
      <?php endForeach; ?>
    </tbody>
    <tfoot class="full-width">
      <tr>
        <th colspan="8">
          <?= $this->linkTo("/categorias/novo", 'Nova categoria', 'class="ui right floated small primary labeled icon button"', 'class="add circle icon"') ?>
        </th>
      </tr>
    </tfoot>
  </table>
</section>
