<section>
  <header>
    <h2><?= $this->title ?></h2>
  </header>
  <?= ViewHelpers::linkTo('/categorias/novo', 'Nova categoria', 'class="btn btn-default"') ?>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Data de criação</th>
      </tr>
    </thead>
    <tbody>
    <?php
      foreach ($this->categories as $category): ?>
      <tr>
        <td><?= $category->getId() ?></td>
        <td><?= $category->getName() ?></td>
        <td><?= ViewHelpers::dateFormat($category->getCreatedAt()); ?></td>
        <td><?= ViewHelpers::linkTo("/categorias/{$category->getId()}/editar", "Editar", 'class="btn btn-primary"') ?></td>
        <td><?= ViewHelpers::linkTo("/categorias/{$category->getId()}/deletar", "Excluir", 'class="btn btn-danger"') ?></td>
      </tr>
    <?php endForeach; ?>
    </tbody>
  </table>

</section>
