<section>
  <header>
    <div class="ui equal width grid">
      <div class="column">
        <h2><?= $this->title ?></h2>
      </div>
      <div class="column">
        <?= ViewHelpers::linkTo("/categorias/novo", 'Nova categoria', 'class="ui right floated primary labeled icon button"', 'class="add circle icon"') ?>
      </div>
    </div>
  </header>

  <article>
    <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Data de criação</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->categories as $category): ?>
        <tr>
          <td><?= $category->getId() ?></td>
          <td><?= $category->getName() ?></td>
          <td><?= ViewHelpers::dateFormat($category->getCreatedAt()); ?></td>
          <td>
            <?= ViewHelpers::linkTo("/categorias/{$category->getId()}",'', '', 'class="zoom icon"') ?>
            <?= ViewHelpers::linkTo("/categorias/{$category->getId()}/editar", '', '', 'class="edit icon"') ?>
            <?= ViewHelpers::linkTo("/categorias/{$category->getId()}/deletar", '', 'data-confirm="Deseja excluir categoria?"', 'class="trash icon"') ?>
          </td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>
  </article>
</section>
