<section>
  <header class="ui dividing header">
    <h2>Visualizar categoria</h2>
  </header>
  <article>
    <div class="ui form">
      <div class="field">
        <label for="category_name">Nome</label>
        <input type="text" id="category_name" name="category[name]" placeholder="Digite o nome da categoria" value="<?= $this->category->getName() ?>" disabled>
      </div>
        <?= ViewHelpers::linkTo("/categorias", 'Voltar', 'class="ui left small labeled icon button"', 'class="reply icon"') ?>
    </div>
  </form>
  </article>
</section>
