<section>
      <table class="ui compact celled definition table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Preço</th>
          <th>Categoria</th>
          <th>Data de criação</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
          foreach ($this->products as $product): ?>
          <tr>
            <td><?= $product->getId() ?></td>
            <td><?= $product->getName() ?></td>
            <td><?= $product->getAmount() ?></td>
            <td><?= $product->getPrice() ?></td>
            <td><?= $product->getCategory()->getName() ?></td>
            <td><?= ViewHelpers::dateFormat($product->getCreatedAt()); ?></td>
            <td>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}", '', '', 'class="zoom icon"') ?>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}/editar", '', '', 'class="edit icon"') ?>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}/deletar", '', 'data-confirm="Deseja excluir produto?"', 'class="trash icon"') ?>
            </td>
          </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <th colspan="8">
            <?= ViewHelpers::linkTo("/produtos/novo", 'Novo produto', 'class="ui left floated small primary labeled icon button"', 'class="add circle icon"') ?>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

</section>
