<section>
    <header class="ui dividing header">
      <h2><?= $this->title ?></h2>
    </header>

  <article>
      <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th colspan="5">
            <?= ViewHelpers::linkTo($this->url, $this->link, 'class="ui right small primary labeled icon button"', $this->icon) ?>
          </th>
          <th colspan="3">
            <form action="<?= ViewHelpers::urlFor($this->action) ?>" method="GET">
              <div class="ui action input">
                <input type="text" placeholder="procurar produto..." name="product[name]">
                <button class="ui button" type="submit">Procurar</button>
              </div>
            </form>
          </th>
        </tr>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Preço</th>
          <th>Categoria</th>
          <th>Data de criação</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
          foreach ($this->products as $product): ?>
          <tr>
            <td><?= $product->getId() ?></td>
            <td><?= ViewHelpers::truncate($product->getName()) ?></td>
            <td><?= $product->getAmount() ?></td>
            <td><?= ViewHelpers::currencyFormat($product->getPrice()) ?></td>
            <td><?= $product->getCategory()->getName() ?></td>
            <td><?= ViewHelpers::dateFormat($product->getCreatedAt()); ?></td>
            <td>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}", '', '', 'class="zoom icon"') ?>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}/editar", '', '', 'class="edit icon"') ?>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}/deletar", '', 'data-confirm="Deseja excluir produto?"', 'class="trash icon"') ?>
            </td>
          </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <tr>
            <th colspan="8">
              <div class="ui right floated pagination menu">
                <a class="icon item">
                  <i class="left chevron icon"></i>
                </a>
                <a class="item">1</a>
                <a class="item">2</a>
                <a class="item">3</a>
                <a class="item">4</a>
                <a class="icon item">
                  <i class="right chevron icon"></i>
                </a>
              </div>
            </th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

</article>
</section>
