<section>
    <header>
      <div class="ui equal width grid">
        <div class="column">  <h2><?= $this->title ?></h2></div>
        <div class="column"><?= ViewHelpers::linkTo($this->url, $this->link, 'class="ui right small primary labeled icon button"', $this->icon) ?></div>
        <div class="column">
          <form action="<?= ViewHelpers::urlFor($this->action) ?>" method="GET">
            <div class="ui action input">
              <input type="text" placeholder="procurar produto..." name="product[name]">
              <button class="ui button" type="submit">Procurar</button>
            </div>
          </form>
        </div>
      </div>
    </header>

  <article>
      <table class="ui selectable celled table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Preço</th>
          <th>Categoria</th>
          <th>Data de criação</th>
          <th>Opções</th>
        </tr>
      </thead>
      <tbody>
        <?php
          foreach ($this->products as $product): ?>
          <tr>
            <td><?= $product->getId() ?></td>
            <td><?= ViewHelpers::truncate($product->getName()) ?></td>
            <td><?= $product->getAmount() ?></td>
            <td><?= ViewHelpers::currencyFormat($product->getPrice()) ?></td>
            <td><?= $product->getCategory()->getName() ?></td>
            <td><?= ViewHelpers::dateFormat($product->getCreatedAt()); ?></td>
            <td>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}", '', '', 'class="zoom icon"') ?>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}/editar", '', '', 'class="edit icon"') ?>
              <?= ViewHelpers::linkTo("/produtos/{$product->getId()}/deletar", '', 'data-confirm="Deseja excluir produto?"', 'class="trash icon"') ?>
            </td>
          </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="8"><h4 class="pull-right"> Mostrando <?= count($this->products) ?> produtos de <?= $this->totalOfRegisters ?> </h4></th>
        </tr>
      </tfoot>
    </table>

    <div class="ui centered grid">
    <div class="ui pagination menu">

      <a class="icon item" href="<?= ViewHelpers::urlFor("/produtos/page/1")?>">
        <i class="left chevron icon"></i>
      </a>

      <?php for($i = 1; $i <= $this->totalOfPages; $i++) {
        $class = $i == $this->page ? 'active' : '';
        $url = ViewHelpers::urlFor("/produtos/page/{$i}");
        echo "<a class=\"item {$class}\" href=\"{$url}\"> {$i} </a>";
      } ?>

      <a class='icon item' href="<?= ViewHelpers::urlFor("/produtos/page/{$this->totalOfPages}") ?>">
        <i class='right chevron icon'></i>
      </a>

    </div>
</div>




</article>
</section>
