<section>
  <header class="ui dividing header">
    <h2><?= $this->title ?></h2>
  </header>
  <article>

    <div class="ui segment">

      <table class="ui celled table">
        <thead>
          <tr>
            <th>ID</th>
            <th><?= $this->product->getId() ?></th>
          </tr>
          <tr>
            <th>Name</th>
            <th><?= $this->product->getName() ?></th>
          </tr>
          <tr>
            <th>Quantidade</th>
            <th><?= $this->product->getAmount() ?></th>
          </tr>
          <tr>
            <th>Preço</th>
            <th><?= ViewHelpers::currencyFormat($this->product->getPrice()) ?></th>
          </tr>
          <tr>
            <th>Categoria</th>
            <th><?= $this->product->getCategory()->getName() ?></th>
          </tr>
          <tr>
            <th>Descrição</th>
            <th><?= $this->product->getDescription() ?></th>
          </tr>
          <tr>
            <th>Data de criação</th>
            <th><?= ViewHelpers::dateFormat($this->product->getCreatedAt()); ?></th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>

      <div class="ui buttons">
        <?= ViewHelpers::linkTo("/produtos", 'Voltar', 'class="ui left floated small labeled icon button"', 'class="reply icon"') ?>
      </div>
    </div>
  </div>

</article>
</section>
