<form class="ui form reports" action="<?= $this->action ?>" method="GET">
  <div class="three fields">
    <div class="required field">
      <label>Data inicial</label>
      <input type="date" id="report_created_at" name="report[created_at]" placeholder=" ** / ** / ****" value="">
    </div>

    <div class="required field">
      <label>Data final</label>
      <input type="date" id="report_closed_at" name="report[closed_at]" placeholder=" ** / ** / ****" value="">
    </div>

    <div class="required field">
      <label></label>
      <?= ViewHelpers::buttonTo($this->submit, 'class="ui right labeled icon primary button"', 'class="right arrow icon"') ?>
    </div>
  </div>
</form>
