
  <table class="ui compact celled definition table">
      <thead class="full-width">
        <tr>
          <th></th>
          <th>Produto</th>
          <th>Preço do produto</th>
          <th>Quantidade de vendas</td>
          <th>Valor total das vendas</td>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->reports as $report): ?>
        <tr>
          <td><?= $report->getProduct()->getId() ?></td>
          <td><?= $report->getProduct()->getName() ?></td>
          <td><?= ViewHelpers::currencyFormat($report->getProduct()->getPrice()) ?></td>
          <td><?= $report->getAmount() ?></td>
          <td><?= ViewHelpers::currencyFormat($report->getTotal()) ?></td>
        </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot class="full-width">

      </tfoot>
    </table>
  </div>
</div>
