<section>
  <?php require "_header.phtml" ?>

  <article>
    <table class="ui compact celled definition table">
      <thead class="full-width">
        <tr>
          <th>ID</th>
          <th>Funcionário</th>
          <th>Quantidade de pedidos</td>
          <th>Valor total das vendas</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($this->reports as $report): ?>
        <tr>
          <td><?= $report->getEmployee()->getId() ?></td>
          <td><?= $report->getEmployee()->getName() ?></td>
          <td><?= $report->getAmount() ?></td>
          <td><?= ViewHelpers::currencyFormat($report->getTotal()) ?></td>
        </tr>
        <?php endForeach; ?>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <th colspan="8">
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
</article>
<div id="graphicBestSellingProducts" data-graphicData='<?= $this->graphics ?>'></div>
</section>
